spring:
 application:
  name: yellow_movement
 boot:
    admin:
      client:
        url: https://yellow-movement-admin.cfapps.io

 datasource: 
    url: jdbc:mysql://localhost/yellow_movement_site
    username: yellow_movement_user
    password: P@$$w0rd
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

 jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
          scripts:
            action: none
            create-target: yellow_movement_db_create.sql

 servlet:
     multipart:
      max-request-size: 10MB
      max-file-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "*"